//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.Rap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.Rap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///uživatel {0} si právě zarezervoval zdroj {1} na {2}.
        ///
        ///Tuto zprávu dostáváte, protože jste si to vyžádali v nastavení rezervačního systému. Nastavení můžete kdykoliv změnit na adrese {3}
        ///
        ///--
        ///Správce systému.
        /// </summary>
        internal static string BookingCreateBody {
            get {
                return ResourceManager.GetString("BookingCreateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová rezervace: {0}, {1}, {2}.
        /// </summary>
        internal static string BookingCreateSubject {
            get {
                return ResourceManager.GetString("BookingCreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///uživatel {1} přidal na nástěnku novou zprávu {0}:
        ///
        ///{2}
        ///
        ///Tuto zprávu dostáváte, protože jste si to vyžádali v nastavení rezervačního systému. Nastavení můžete kdykoliv změnit na adrese {3}
        ///
        ///--
        ///Správce systému.
        /// </summary>
        internal static string MessageCreateBody {
            get {
                return ResourceManager.GetString("MessageCreateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová zpráva na nástěnce: {0}.
        /// </summary>
        internal static string MessageCreateSubject {
            get {
                return ResourceManager.GetString("MessageCreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///byl vám vytvořen nový účet pro přístup do rezervačního systému &apos;{0}&apos;. Pro přihlášení použijte následující údaje:
        ///
        ///Adresa: {1}
        ///Uživatelské jméno: {2}
        ///Heslo: {3}
        ///
        ///Důrazně vám doporučujeme ihned po přihlášení změnit heslo!
        ///
        ///--
        ///Správce systému.
        /// </summary>
        internal static string UserCreateBody {
            get {
                return ResourceManager.GetString("UserCreateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup do rezervačního systému.
        /// </summary>
        internal static string UserCreateSubject {
            get {
                return ResourceManager.GetString("UserCreateSubject", resourceCulture);
            }
        }
    }
}
